# Errata {-}
<div style="text-align: justify">
Na tabela abaixo são apresentadas algumas correções feitas no texto do livro, tanto em erros localizados pelos autores como por leitores que tiveram a gentileza de nos comunicar. Os erros podem aparecer em versões que, eventualmente, possam ter sido baixadas por leitores antes das datas que aparecem na coluna "Data".    
Caso deseje comunicar algum problema encontrado ou sugestão, favor enviar e-mail para Pedro Luis do Nascimento Silva: <pedronsilva@gmail.com> ou Antonio José Ribeiro Dias: <vermelho2@gmail.com>.

---------------
Item            Data       Versão corrigida
--------------- ---------- --------------------------------------------------------------------------------------------------------------------------------------------------------
Exemplo 4.4     10/11/2020 (dp_med_amo <- sqrt(var_med_amo))

Exemplo 4.4     10/11/2020 (cv_med_amo <- 100 * dp_med_amo / med_amo)

Equação 10.18   18/01/2021 $\widehat V_{AP} \left(\widehat Y_{AP}\right) =\displaystyle \frac{n}{n-1} \displaystyle\sum_{i \in s} \left(\frac{y_i}{\lambda_i} - \frac{\sum_{k \in s} y_k(1-\lambda_k)/\lambda_k} {\sum_{k \in s} (1-\lambda_k)}\right)^2 (1-\lambda_i)$

GSBPM. (2013)   29/01/2021  Generic Statistical Business Process Model: GSBPM: version 5.0 
---------------
